"""Security helpers shared by the RepoAnalyzer API and analysis pipeline."""

from __future__ import annotations

import ipaddress
import os
import re
import socket
import uuid
from pathlib import Path
from urllib.parse import urlparse

from fastapi import HTTPException


SESSION_ID_PATTERN = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$")
ALLOWED_GIT_HOSTS = {
    host.strip().lower()
    for host in os.getenv(
        "ALLOWED_GIT_HOSTS", "github.com,gitlab.com,bitbucket.org"
    ).split(",")
    if host.strip()
}
MAX_FILE_SIZE_BYTES = int(os.getenv("MAX_ANALYZED_FILE_BYTES", "2000000"))
MAX_FILES_PER_REPOSITORY = int(os.getenv("MAX_FILES_PER_REPOSITORY", "10000"))
MAX_SOURCE_RESPONSE_BYTES = int(os.getenv("MAX_SOURCE_RESPONSE_BYTES", "1000000"))


def validate_session_id(value: str) -> str:
    """Accept only the UUIDv4 values generated by the browser session helper."""
    normalized = value.strip().lower()
    if not SESSION_ID_PATTERN.fullmatch(normalized):
        raise HTTPException(status_code=400, detail="Invalid session identifier.")
    try:
        uuid.UUID(normalized, version=4)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail="Invalid session identifier.") from exc
    return normalized


def _is_within(child: Path, parent: Path) -> bool:
    try:
        child.relative_to(parent)
        return True
    except ValueError:
        return False


def resolve_local_repository(raw_path: str) -> Path:
    """Resolve a local scan path and keep it below the configured scan root."""
    scan_root = Path(os.getenv("REPO_SCAN_ROOT", str(Path.home()))).expanduser().resolve()
    candidate = Path(raw_path).expanduser().resolve(strict=True)
    if not candidate.is_dir():
        raise HTTPException(status_code=400, detail="Repository path must be a directory.")
    if not _is_within(candidate, scan_root):
        raise HTTPException(
            status_code=400,
            detail="Local repository paths must be inside the configured scan root.",
        )
    return candidate


def safe_repo_file(repo_path: str | Path, relative_path: str) -> Path:
    """Resolve a repository-relative file and reject traversal or symlink escapes."""
    base = Path(repo_path).resolve(strict=True)
    target = (base / relative_path).resolve(strict=True)
    if not _is_within(target, base) or not target.is_file():
        raise HTTPException(status_code=404, detail="Repository file not found.")
    return target


def validate_git_source(raw_url: str) -> str:
    """Allow public HTTPS Git URLs without permitting arbitrary network targets."""
    value = raw_url.strip()
    parsed = urlparse(value)
    if parsed.scheme != "https" or not parsed.hostname:
        raise HTTPException(status_code=400, detail="Use a public HTTPS Git repository URL.")
    host = parsed.hostname.lower().rstrip(".")
    if host not in ALLOWED_GIT_HOSTS:
        raise HTTPException(status_code=400, detail="Git host is not on the approved allowlist.")
    if parsed.username or parsed.password or parsed.port:
        raise HTTPException(status_code=400, detail="Git URLs must not include credentials or ports.")
    try:
        addresses = {item[4][0] for item in socket.getaddrinfo(host, 443, type=socket.SOCK_STREAM)}
        for address in addresses:
            ip = ipaddress.ip_address(address)
            if ip.is_private or ip.is_loopback or ip.is_link_local or ip.is_reserved:
                raise HTTPException(status_code=400, detail="Git host resolves to a private network.")
    except socket.gaierror as exc:
        raise HTTPException(status_code=400, detail="Git host could not be resolved.") from exc
    return value


def display_repository_path(path: str) -> str:
    """Avoid returning server filesystem paths to browsers or third-party LLMs."""
    if path.startswith(("https://", "http://", "git@")):
        return path
    return Path(path).name or "local repository"
